### ISSUE TITLE
Common API is broken after combat update

### ISSUE THREAD

**Issue by MeiVinEight** [kremnev8/CommonAPI#7]
Mod crashed in newest version of game
![image](https://github.com/kremnev8/CommonAPI/assets/57023439/7296bb7a-2237-4488-9fdf-8b1da003e8e6)

**Comment by kremnev8** [comment]
Of course it doesn't work. The devs have released a big update. Please be patient with me. The update will come, but I'm unable to give an ETA.

**Comment by SGZ-Creations** [comment]
Want to give some more info in case u haven't see this yet.
![image](https://github.com/kremnev8/CommonAPI/assets/59801736/ddd5c90c-246f-4ba5-ba07-bdfb640be8f4)

**Comment by kremnev8** [comment]
> Want to give some more info in case u haven't see this yet. ![image](https://private-user-images.githubusercontent.com/59801736/292668447-8cb48fed-a97b-4cd4-9771-1e44f04c4d14.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0MTk1NDYsIm5iZiI6MTcwMzQxOTI0NiwicGF0aCI6Ii81OTgwMTczNi8yOTI2Njg0NDctOGNiNDhmZWQtYTk3Yi00Y2Q0LTk3NzEtMWU0NGYwNGM0ZDE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDEyMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1MTZjZmY2MDlmNGY4OTExZDdhNDE4NDk1ODI2OGI4NjEyOGQ3ZmQ0ZDUwMjlmMmEwZmM4YTE3MzkwNzA3YzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.205MkFM4zHfSNBrDUSDUgTfyaKsIIMBDtHxA0QkStfM)

This warning message is irrelevant, and can be safely ignored

**Comment by kremnev8** [comment]
Common API was updated for combat update in v1.6.0
