### ISSUE TITLE
Does This mod requires the NebulaMultiplayerModApi to work?

### ISSUE THREAD

**Issue by HehCrashes** [kremnev8/CommonAPI#8]
When I develop mods using CommonAPI, I find the mod need NebulaMultiplayerModApi to function :
![2072eb0683ad89d04a055b38ab9c000a](https://github.com/kremnev8/CommonAPI/assets/85434067/633f7bb5-63f2-4bbf-9119-993f77930393)

But the mod is unneeded according to Thunderstore(https://dsp.thunderstore.io/package/CommonAPI/CommonAPI/)

**Comment by kremnev8** [comment]
No.
What's happening in your case is that you must have installed the mod incorrectly. Did you place the preloader into preloader folder?
