### ISSUE TITLE
filterItem

### ISSUE THREAD

**Issue by ByboyCn** [kremnev8/CommonAPI#9]
I want to get a filter for all the items. What should I do?

**Comment by ByboyCn** [comment]
The first thing that comes to mind is `UIItemPickerExtension.Popup (new Vector2 (- 300f250f), OnReturn,itemProto = > true);` but it doesn't work, and its display is still limited by technology.

**Comment by kremnev8** [comment]
You can use vanilla signal picker. Or maybe limit it by item type. Check how logistics stations implement their item selection.
But I'm doubtful any of the pickers support showing locked items.

**Comment by ByboyCn** [comment]
The signal picker is fine, but it returns a value of type `int`.  How do I convert it to `item.ID`?
